### PR TITLE
Showcase of Components.

### PR DESCRIPTION
**Pull request by bmoneke**
This is a **showcase** how some Components could be implemented (I use them in my lab). Merging will take place in smaller PRs.

This is a working version of Coordinator and some utils according to https://github.com/pymeasure/leco-protocol/pull/38

As the message Layer is still under development, I used json with a list of commands, each command is again a list with a command type and optionally more information. For example a set command and an acknowledgement (I have a StrEnum for the command type):
~~~python
[["S", {'property1': 7}]]
[["A"]]
[["S", {'property1': 7}], ["G", ["property1"]]  # this sets a value and gets it afterwards.
~~~

I can also upload an Actor and more, but they are not as polished as the Coordinator (but they do their job in the lab).

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Very nice first step, thank you! It will take sometime until I can take a look through. :-/

In the meantime I will try to get CI set up so that we can run some checks against this.

**Comment by bmoneke** [comment]
I was not even looking for a rough review, just for a help, how an implementation might look like.
This can help Form the protocol and to understand, how I understand the protocol.

Obviously I'm glad for feedback, when you look at the code (especially those general things like filenames and structure).

**Comment by bilderbuchi** [comment]
Alles klar! 
One thing that might be useful to catch more shortcomings of the spec is to implement pyleco "by the book", i.e. following the specification as written (not as we know it in our head). 
I know such detachment is probably gonna be difficult as we also wrote the spec, but during review reviewers should probably compare to the spec regularly.

**Comment by bmoneke** [comment]
In fact, yesterday I added tests according to the leco specifications (in the leco pr) and found a mistake (which is still in this PR).

I reworked the Coordinator according to the specs (including tests) before creating this PR.

**Comment by bmoneke** [comment]
I added an Actor (still called "Controller" in my implementation) and the Data Protocol Proxy Server and a Data Protocol Publisher.

I consider this PR as a _showcase_ of my current code and do not intend to merge this PR at all.

For serious review processes (intended for merging), I will use individual PRs.

**Comment by bmoneke** [comment]
Now the communication is done via jsonrpc messages.

**Comment by bilderbuchi** [comment]
I think, effectively, you have become the primary dev of pyleco. I don't know when I would find the time to review a 7k lines beast of a PR meaningfully. @bklebel how about you?
Considering that, do you want to just merge this into `main` unreviewed, and do any further changes as more PRs (or however best). I'm prepared to take this one on trust in your ability. :-)

**Comment by bklebel** [comment]
I agree. I would very much like to work together on this code, and contribute a significant part, but quite frankly, my responsibilities in our research group have changed a bit, so that I cannot implement pyleco in our lab right now and supplant the backend of CryostatGUI with it right now, even if I would much prefer to do so over some other responsibilities. However, only doing this would really enable me (right now) to contribute meaningfully, since then I would really have the time to look into it. 

I really like what you built here @bmoneke, so for now, also from my side, feel free to merge, and and I very much hope I can contribute more in the future.

**Comment by bmoneke** [comment]
Ok. My idea is, to merge it in small parts.
In the PRs I'm going to ask you questions regarding structure (i.e. separation of folders / modules, naming schemes etc.) instead of a full code review.
Until now, you have to import every class from its module, there are no shortcuts like `pymeasure.instrument` yet (code will continue to work, if a shortcut is added, but not if it is removed).

**Comment by bklebel** [comment]
Okay, that sounds like a good way to proceed, I'm up for it.

**Comment by bmoneke** [comment]
Superseded by #10 due do branch name change.

**Pull request closed without merging**
