### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by BenediktBurger**
Address some issues from #40

### CODE REVIEW

**Comment by BenediktBurger** [comment]
I added (mermaid) flow charts to the `GETTING_STARTED.md` to make it easier to understand, how the different components work together.

The diagram information is only additional to the text, so if it does not render, it is only a small part of source code to skip.
The readme links to the `GETTING_STARTED.md` on github, and github can render mermaid, which should work well.

What do you think, @bilderbuchi , @bklebel ?

**Comment by bilderbuchi** [comment]
I think it's no problem to add mermaid blocks.

**Comment by bklebel** [comment]
looks quite nice! :)

**Comment by BenediktBurger** [comment]
Thanks!

**Pull request merged**
