### PR TITLE
Add codecov to CI

### PR DESCRIPTION
**Pull request by BenediktBurger**
Codecov seems to work even for other users forks.

This PR adds codecov (and probably removes the other one).

- [x] It requires, however, the installation of the Codecov app on GitHub for the pymeasure organization? Here's the link: https://github.com/apps/codecov/installations/select_target
@bilderbuchi  can you do that, or just @cjermain ?
- [ ] And it requires to add a token to the repo secrets.
- [ ] Remove the old code coverage from the ci file and the README (badge)

Maybe it's useful for pymeasure as well?

### CODE REVIEW

**Comment by cjermain** [comment]
I'm a fan of Codecov and used it for a recent project ([rust-python-coverage](https://github.com/cjermain/rust-python-coverage)). I've enabled Codecov for all PyMeasure org repos. I'll circle back on a token in the repo secrets. @BenediktBurger or @bilderbuchi , can either of you access the token creation through the PyMeasure org permissions?
https://app.codecov.io/gh/pymeasure

**Comment by BenediktBurger** [comment]
> can either of you access the token creation through the PyMeasure org permissions?

I do not have access to the `settings` part of the pymeasure repos.

**Comment by BenediktBurger** [comment]
Thanks @cjermain for adding codecov

**Comment by cjermain** [comment]
I've added the appropriate secret token to both this repo and pymeasure.

**Comment by BenediktBurger** [comment]
Thanks

**Comment by bilderbuchi** [comment]
> > can either of you access the token creation through the PyMeasure org permissions?
> 
> I do not have access to the `settings` part of the pymeasure repos.

same here.

Thanks for adding this! I agree it could be useful for pymeasure, too.

**Pull request merged**
